cmo_phrase_variations = [
    "CMO",
    "cmo",
    "Chief Marketing Officer",
    "chief marketing officer",
    "Chief marketing officer",
]

media_types = [
    "Behind-the-Scenes",
    "Channels",
    "Clips",
    "Conversations",
    "Demos",
    "Discussions",
    "Documentaries",
    "Episodes",
    "Expert-Panels",
    "Highlights and Recaps",
    "Influencer Collaborations",
    "Infographics",
    "Insights",
    "Interviews",
    "Live Streams",
    "Meetings",
    "Playlists",
    "Podcasts",
    "Product Reviews",
    "Reviews",
    "Shorts",
    "Speeches",
    "Stories",
    "Talks",
    "Training Sessions",
    "Tutorials",
    "Videos",
    "Virtual Events",
    "Vlogs",
    "Webinars",
]


cmo_adjectives = [
    "Agile",
    "Agile-Marketer",
    "Analytical",
    "Brand-Building",
    "Collaborative",
    "Consumer-Behavior-Understanding",
    "Creative",
    "Cross-Functional",
    "Customer Experience-Centric",
    "Customer-Insight-Driven",
    "Customer-Journey-Focused",
    "Customer-Lifecycle-Oriented",
    "Customer-Loyalty-Building",
    "Data-Driven",
    "Data-Intelligent",
    "Digital-Savvy",
    "Disruptive",
    "Dynamic",
    "Forward-Thinking",
    "Growth-Enabler",
    "Growth-Oriented",
    "Innovative",
    "Innovative-Strategist",
    "Market-Leading",
    "Market-Research-Saavy",
    "Multi-Channel",
    "Omnichannel",
    "Personalized",
    "Performance-Measured",
    "Revenue-Generating",
    "ROI-Focused",
    "ROI-Optimizing",
    "Solution-Oriented",
    "Strategic",
    "Tech-Adaptive",
    "Trend-Setting",
    "Visionary",
]


cmo_responsibilities = [
    "Advertising",
    "Brand Management",
    "Brand Positioning",
    "Budget Management",
    "Community Engagement",
    "Competitor Analysis",
    "Content Marketing",
    "Crisis Communications",
    "Cross-Department Collaboration",
    "Customer Engagement",
    "Customer Experience",
    "Customer Insights",
    "Customer Loyalty",
    "Customer Retention",
    "Customer Satisfaction",
    "Data Analytics",
    "Data Privacy Compliance",
    "Demand Generation",
    "Digital Marketing",
    "Email Marketing",
    "Event Marketing",
    "Event Representation",
    "Growth Strategies",
    "Influencer Marketing",
    "Industry Trends",
    "Innovation Culture",
    "Lead Generation",
    "Lead Nurturing",
    "Market Opportunities",
    "Market Research",
    "Market Segmentation",
    "Marketing Automation",
    "Marketing Campaigns",
    "Marketing Strategies",
    "Marketing Technology",
    "Media Buying",
    "Paid Advertising",
    "Partnerships",
    "Performance Tracking",
    "Product Marketing",
    "Public Relations",
    "Public Speaking",
    "Regulatory Compliance",
    "Reputation Management",
    "Sales Enablement",
    "Search Engine Optimization (SEO)",
    "Social Listening",
    "Social Media",
    "Storytelling",
    "Target Audiences",
    "Team Management",
    "Thought Leadership",
    "User Experience (UX) Design",
    "Vendor Management",
    "Web Analytics",
]
